# Install the relevant packages 
.libPaths(c(Sys.getenv("R_LIBS_USER"), .libPaths()))

options(timeout=600)
install.packages("shiny")
install.packages("shinydashboard")
install.packages("hesim")
install.packages("data.table")
install.packages("ggplot2")
install.packages("survminer")
install.packages("shinyWidgets")
install.packages("rmarkdown")
install.packages("bookdown")
install.packages("knitr")
install.packages("kableExtra")
install.packages("diagram")
install.packages("heemod")
install.packages("shinyclassloaders")
install.packages("DT")
install.packages("shinyjs")
install.packages('BCEA', repos = c('https://giabaio.r-universe.dev', 'https://cloud.r-project.org'))
