#########################################
# Set up and common commands & packages #
#########################################

# This is a hack to insert 'alt-text' in images created by the R chunks
# source: https://ropensci.org/technotes/2020/04/23/rmd-learnings/
# NB: the 'alt-text' needs to be **'title'** attribute that gets included in the list 'opts'
# which is included as part of the set up in the chunk, for example
#    ```{r echo=FALSE,opts=list(title="Alt-text",width="45%"...)}
# (see: https://www.computerhope.com/issues/ch001076.htm).
# Also, needs to specify the 'width' option (= what would normally be 'out.width') to ensure
# that the resulting HTML code to format the graph
knitr::knit_hooks$set(
  plot = function(x, options) {
    opts <- options$opts
    paste0(
      "<img src=",
      '"', x, '" ',
      if (!is.null(opts)) {
        # Here include the styling for the graphs - this ensure it's centered
        paste('style="display: block; margin: auto;"',
              # And this "glues" the options passed by the user (including the 'alt-text')
              glue::glue_collapse(glue::glue('{names(opts)}="{opts}"'),sep = " ")
        )
      },
      ">\n"
    )
  },
  # This sets up a switch that allows to automatically crop the images generated by R
  # https://bookdown.org/yihui/rmarkdown-cookbook/crop-plot.html
  knitr::knit_hooks$set(crop = knitr::hook_pdfcrop)
)

# Defaults for figure size
# fig.retina=3 improves the quality of the resulting graph (https://arm.rbind.io/slides/xaringan.html#89)
knitr::opts_chunk$set(fig.width=10, fig.height=9, out.width="55%", fig.align='center', fig.retina=3, crop=TRUE,
                      comment=NA,message=FALSE,error=FALSE)



# This sets up the figure path so that all the R-generated images are stored under 'img'
knitr::opts_chunk$set(fig.path="./img/")

# Relevant packages (to load globally - not for a single slide)
library(dplyr)
library(ggplot2)
library(kableExtra)
library(slides)

# Formats the date in the title-slide
# If the date is specified as a string (to a specific value), then used that, else use current date
if(!is.null(rmarkdown::metadata$params$date)){date=rmarkdown::metadata$params$date} else {date=format(Sys.Date(),"%e %B %Y")}

# Also creates a variable 'short_date' that can be used in the footers
short_date=format(as.Date(date,format="%e %b %Y"),"%e %b %Y")

logo_stats=function(url="assets/images/UCL_Stats_logo.jpeg"){
  paste0(
    "<p style='position: absolute; top: 86.0%; left: 92.0%; text-decoration:none; display:block; 
    height: 3.5em; width: 3.5em; padding: .5em; box-shadow: 5px 5px 7px rgba(33,33,33,.7);
    background-image: url(\"",url,"\"); background-size: contain; border-radius: 6px 6px 6px 6px;'></p>"
  )
}

# Citations & Bibliography (https://github.com/yihui/xaringan/wiki/Bibliography-and-citations)
# RefManageR: https://arxiv.org/pdf/1403.2036v1.pdf
# library(RefManageR)
# RefManageR::BibOptions(check.entries = FALSE,
#             bib.style = "authoryear",
#             style = "markdown",
#             cite.style = "authoryear",
#             super = FALSE,
#             hyperlink = FALSE,
#             dashed = FALSE
#             #           bibpunct = c("(",")","(",")",";",","),
# )
# NOT NEEDED WITH quarto!

